# Generated by Django 4.0.2 on 2022-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Adventures', 'Adventure'), ('all', 'ALL'), ('Love', 'Love')], max_length=50),
        ),
    ]
