# Generated by Django 4.0.2 on 2022-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('all', 'ALL'), ('Love', 'Love'), ('Adventures', 'Adventure')], max_length=50),
        ),
    ]
