# Generated by Django 4.0.2 on 2022-02-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('My Life', 'ALL'), ('Adventures', 'Adventure'), ('Love', 'Love')], max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
