# Generated by Django 4.0.2 on 2022-02-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_category_name_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Love', 'Love'), ('Adventures', 'Adventure'), ('My Life', 'ALL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
